export {HomeComponents} from './Home/Home'
export {Techtransfer} from './Techtransfer/Techtransfer'
export {Earth} from './Earth/Earth'
export {Apod} from './Apod/Apod'
export {AboutUs} from './AboutUs/AboutUs'